<?php
add_action( 'acf/include_fields', function() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    acf_add_local_field_group( array(
        'key' => 'group_faq_accordion',
        'title' => 'FAQ Accordion',
        'fields' => array(
            array(
                'key' => 'field_faq_accordion',
                'label' => 'FAQ Accordion',
                'name' => 'faq_accordion',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_faq_accordion_items_left',
                        'label' => 'Left Column Items',
                        'name' => 'items_left',
                        'aria-label' => '',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'pagination' => 0,
                        'min' => 0,
                        'max' => 0,
                        'collapsed' => '',
                        'button_label' => 'Add FAQ Item',
                        'rows_per_page' => 20,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_faq_accordion_item_category',
                                'label' => 'Category Class',
                                'name' => 'category',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => 'CSS class for filtering (e.g., buying, community, author)',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'parent_repeater' => 'field_faq_accordion_items_left',
                            ),
                            array(
                                'key' => 'field_faq_accordion_item_title',
                                'label' => 'Title',
                                'name' => 'title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'parent_repeater' => 'field_faq_accordion_items_left',
                            ),
                            array(
                                'key' => 'field_faq_accordion_item_content',
                                'label' => 'Content',
                                'name' => 'content',
                                'aria-label' => '',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'rows' => 4,
                                'placeholder' => '',
                                'new_lines' => '',
                                'parent_repeater' => 'field_faq_accordion_items_left',
                            ),
                            array(
                                'key' => 'field_faq_accordion_item_icon_svg',
                                'label' => 'Icon SVG',
                                'name' => 'icon_svg',
                                'aria-label' => '',
                                'type' => 'textarea',
                                'instructions' => 'SVG code for icon (19x19 viewBox)',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'rows' => 8,
                                'placeholder' => '',
                                'new_lines' => '',
                                'parent_repeater' => 'field_faq_accordion_items_left',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_faq_accordion_items_right',
                        'label' => 'Right Column Items',
                        'name' => 'items_right',
                        'aria-label' => '',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'pagination' => 0,
                        'min' => 0,
                        'max' => 0,
                        'collapsed' => '',
                        'button_label' => 'Add FAQ Item',
                        'rows_per_page' => 20,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_faq_accordion_item_category_right',
                                'label' => 'Category Class',
                                'name' => 'category',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => 'CSS class for filtering (e.g., buying, community, author)',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'parent_repeater' => 'field_faq_accordion_items_right',
                            ),
                            array(
                                'key' => 'field_faq_accordion_item_title_right',
                                'label' => 'Title',
                                'name' => 'title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'parent_repeater' => 'field_faq_accordion_items_right',
                            ),
                            array(
                                'key' => 'field_faq_accordion_item_content_right',
                                'label' => 'Content',
                                'name' => 'content',
                                'aria-label' => '',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'rows' => 4,
                                'placeholder' => '',
                                'new_lines' => '',
                                'parent_repeater' => 'field_faq_accordion_items_right',
                            ),
                            array(
                                'key' => 'field_faq_accordion_item_icon_svg_right',
                                'label' => 'Icon SVG',
                                'name' => 'icon_svg',
                                'aria-label' => '',
                                'type' => 'textarea',
                                'instructions' => 'SVG code for icon (19x19 viewBox)',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'maxlength' => '',
                                'rows' => 8,
                                'placeholder' => '',
                                'new_lines' => '',
                                'parent_repeater' => 'field_faq_accordion_items_right',
                            ),
                        ),
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'block',
                    'operator' => '==',
                    'value' => 'acf/faq-accordion',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );
} );

